gpu: false
whisper_model: medium
whisper_backend: faster-whisper
llm_backend: ollama
wakeword_backend: picovoice
tts_backend: xtts
audio_input_device: default
audio_output_device: default
voice_profile: default
whisper_device: auto
whisper_compute_type: int8
