"""Natural language skill creation from user chat messages.

When a user says "teach yourself to…", "learn how to…", or similar phrases,
:class:`SkillTrainer` generates a Python skill script using the
``SKILL_METADATA`` pattern, writes it to ``plugins/skills/``, and registers
it in the provided :class:`~rex.skills.registry.SkillRegistry`.

Public API
----------
:func:`detect_skill_creation_intent`
    Return the skill intent string from a message, or None.
:class:`SkillTrainer`
    Intercept skill-creation requests and handle the full create/register flow.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from rex.skills.registry import Skill, SkillRegistry

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Intent detection
# ---------------------------------------------------------------------------

_CREATION_PATTERNS: list[str] = [
    r"teach\s+yourself\s+to\s+(.+)",
    r"learn\s+how\s+to\s+(.+)",
    r"add\s+a\s+skill\s+(?:that|to|for)\s+(.+)",
    r"create\s+a\s+skill\s+(?:that|to|for)\s+(.+)",
    r"remember\s+how\s+to\s+(.+)",
    r"make\s+a\s+skill\s+(?:that|to|for)\s+(.+)",
]

_DEFAULT_SKILLS_DIR = Path("plugins/skills")


def detect_skill_creation_intent(message: str) -> str | None:
    """Return the intent description from *message*, or None.

    Strips trailing punctuation before matching so natural spoken/typed
    phrasing ("teach yourself to check the battery.") works correctly.

    Args:
        message: Raw user message.

    Returns:
        The intent phrase (e.g. ``"tell me the current battery level"``) if a
        skill-creation pattern matched, otherwise ``None``.
    """
    clean = message.strip().rstrip(".!?")
    for pattern in _CREATION_PATTERNS:
        match = re.search(pattern, clean, re.IGNORECASE)
        if match:
            return match.group(1).strip().rstrip(".!?")
    return None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _slugify(text: str) -> str:
    """Convert *text* to a snake_case identifier for file/skill names.

    >>> _slugify("Tell me the current battery level")
    'tell_me_the_current_battery_level'
    """
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    text = text.strip("_")
    return text[:48]


def _derive_triggers(intent: str) -> list[str]:
    """Return a list of trigger phrases derived from *intent*.

    Always includes the raw intent.  Adds a shortened form with common filler
    words removed, if that produces a distinct non-empty string.
    """
    base = intent.lower().strip()
    triggers: list[str] = [base]

    stripped = re.sub(
        r"\b(me|the|a|an|my|your|current|now|please)\b", "", base, flags=re.IGNORECASE
    )
    stripped = re.sub(r"\s+", " ", stripped).strip()
    if stripped and stripped != base:
        triggers.append(stripped)

    return [t for t in triggers if t]


def _generate_skill_script(name: str, description: str, triggers: list[str]) -> str:
    """Return the content of a Python skill script for the given parameters."""
    trigger_lines = ",\n        ".join(f'r"{t}"' for t in triggers)
    return f'''"""Rex skill: {name}.

Auto-generated by Rex skill trainer from natural language instruction.
"""

SKILL_METADATA = {{
    "name": "{name}",
    "description": "{description}",
    "triggers": [
        {trigger_lines},
    ],
}}


def run(transcript: str) -> str:
    """Execute the {name!r} skill.

    Args:
        transcript: The full user utterance that triggered this skill.

    Returns:
        A human-readable response.
    """
    # TODO: implement {name}
    return "The {name} skill was triggered but is not yet fully implemented."
'''


# ---------------------------------------------------------------------------
# SkillTrainer
# ---------------------------------------------------------------------------


class SkillTrainer:
    """Handle natural-language skill creation requests.

    When a user message matches a skill-creation intent pattern this trainer:

    1. Derives a skill name, description, and trigger phrases from the message.
    2. Generates a Python skill script using the ``SKILL_METADATA`` pattern.
    3. Writes the script to ``plugins/skills/<slug>.py``.
    4. Registers the skill in the provided :class:`~rex.skills.registry.SkillRegistry`.
    5. Returns a human-readable confirmation string.

    Parameters:
        skills_dir: Directory where skill scripts are written.  Defaults to
            ``plugins/skills/``.
    """

    def __init__(self, skills_dir: Path | str | None = None) -> None:
        self._skills_dir = Path(skills_dir) if skills_dir is not None else _DEFAULT_SKILLS_DIR

    def handle_if_training_request(
        self,
        message: str,
        registry: SkillRegistry,
    ) -> str | None:
        """Intercept *message* if it is a skill creation request.

        Args:
            message: Raw user utterance.
            registry: The registry to register the new skill into.

        Returns:
            A confirmation string if a skill was created, ``None`` if the
            message is not a skill-creation request.
        """
        intent = detect_skill_creation_intent(message)
        if intent is None:
            return None

        name = intent
        slug = _slugify(name)
        description = f"Handles: {name}"
        triggers = _derive_triggers(intent)

        # Write skill script
        script_path = self._skills_dir / f"{slug}.py"
        script_content = _generate_skill_script(name, description, triggers)

        try:
            self._skills_dir.mkdir(parents=True, exist_ok=True)
            script_path.write_text(script_content, encoding="utf-8")
            logger.info("SkillTrainer: wrote skill script to %s", script_path)
        except Exception as exc:
            logger.warning("SkillTrainer: failed to write skill script: %s", exc)
            return f"I tried to learn '{name}' but couldn't save the skill file."

        # Register in registry
        try:
            skill: Skill = registry.register(
                name=name,
                description=description,
                trigger_patterns=triggers,
                handler=str(script_path),
            )
            logger.info("SkillTrainer: registered skill %r (id=%s)", skill.name, skill.id)
        except Exception as exc:
            logger.warning("SkillTrainer: failed to register skill: %s", exc)
            return f"I created the skill file for '{name}' but couldn't register it: {exc}"

        example_trigger = triggers[0] if triggers else name
        return f"I've learned how to {name}. " f'You can trigger it by saying "{example_trigger}".'
